#!/usr/bin/env python3
# Copyright (c) 2026 STAVROPOULOS LAW. All Rights Reserved.
"""Rebuilds MANIFEST.yaml for docs/discovery/frontier-architecture/: SHA-256 and size of every file,
element counts per MFA-* kind, and the snapshot the package was built against.  Never hand-edit
MANIFEST.yaml; run this after every patch (PATCH-PROTOCOL.md §4 step 4)."""
import hashlib, pathlib, re, subprocess, sys, datetime, collections

PKG = pathlib.Path(__file__).resolve().parent.parent
ROOT = pathlib.Path(subprocess.check_output(['git', 'rev-parse', '--show-toplevel'], text=True).strip())
VERSION = sys.argv[1] if len(sys.argv) > 1 else None

def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
files = sorted(p for p in PKG.rglob('*') if p.is_file() and p.name != 'MANIFEST.yaml' and '__pycache__' not in p.parts)
entry = PKG.parent / 'POST-VERDICT-ARCHITECTURE-PLAN.md'
extra = [entry] if entry.exists() else []

# element counts: every "id: MFA-XXX-nnn" in YAML/MD/MMD of the package, deduplicated
ids = collections.Counter()
seen = set()
for p in files:
    if p.suffix not in ('.yaml', '.yml', '.md', '.mmd'): continue
    text = p.read_text(encoding='utf-8')
    if p.suffix == '.md': text = re.sub(r'```.*?```', '', text, flags=re.S)   # examples inside code fences are not elements
    for m in re.finditer(r'(?:^\s*(?:-\s*)?|\{<<: \*\w+, )id:\s*(MFA-[A-Z]+-[A-Za-z0-9-]+)(?=\s*$|,)', text, re.M):
        i = m.group(1)
        if i in seen: continue
        seen.add(i); ids[i.split('-')[1]] += 1

# file-named ids (alternatives, adversarial, diagrams, patches) are counted by filename, not by content
for sub, kind in (('alternatives', 'ALT'), ('adversarial', 'ATK'), ('diagrams', 'DIA'), ('patches', 'PATCH')):
    for p in sorted((PKG / sub).glob('MFA-*')):
        if p.stem not in seen: seen.add(p.stem); ids[kind] += 1
old = (PKG / 'MANIFEST.yaml').read_text(encoding='utf-8') if (PKG / 'MANIFEST.yaml').exists() else ''
m = re.search(r'^package_version:\s*(\S+)', old, re.M)
version = VERSION or (m.group(1) if m else '0.1.0')
head = subprocess.check_output(['git', 'rev-parse', 'HEAD'], text=True, cwd=ROOT).strip()
branch = subprocess.check_output(['git', 'rev-parse', '--abbrev-ref', 'HEAD'], text=True, cwd=ROOT).strip()

out = []
out.append('# MANIFEST — generated by tools/build-manifest.py; do not edit by hand')
out.append('# Copyright (c) 2026 STAVROPOULOS LAW. All Rights Reserved.')
out.append(f'package: docs/discovery/frontier-architecture')
out.append(f'package_version: {version}')
out.append(f'generated_at: {datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")}')
out.append('snapshot:')
out.append(f'  repository: andriannadeepmind-gif/grail-architecture')
out.append(f'  branch: {branch}')
out.append(f'  head: {head}')
out.append('  model_sysml_changed: false')
out.append('  committed: false')
out.append('id_namespace: MFA-*')
out.append('element_counts:')
for k, v in sorted(ids.items()): out.append(f'  {k}: {v}')
out.append(f'  total: {sum(ids.values())}')
out.append('files:')
for p in files + extra:
    rel = p.relative_to(PKG) if p.is_relative_to(PKG) else pathlib.Path('..') / p.name
    out.append(f'  - path: {rel.as_posix()}')
    out.append(f'    bytes: {p.stat().st_size}')
    out.append(f'    sha256: {sha(p)}')
out.append(f'file_count: {len(files) + len(extra)}')
(PKG / 'MANIFEST.yaml').write_text('\n'.join(out) + '\n', encoding='utf-8')
print(f'MANIFEST.yaml: {len(files) + len(extra)} files, {sum(ids.values())} MFA ids, version {version}')
